### ISSUE TITLE
Clarify how whether structures should be brought in using the vw_pip_compatible_inspected_sites

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#12]

**Comment by GeoDan87** [comment]
With the new comfort station workflow, does it make sense to bring structures into the PIP database along with all of the other layers or should it be brought in separately? Recreation Centers and Nature Centers could be added into the Allsites view?

**Comment by MEFParks** [comment]
Just pasting from my e-mail here for posterity:

After discussing with Alex, I don’t think there’s a desire to bring in CSs or any other structure types beyond Rec and Nature centers into Allsites. For CSs the future the plan is to assign values at the Room and CSID level (not the SYSTEM level). We’ll have System in our tables as a reference if we want to do analysis at that level for things like Capital Needs, but bringing them into Allsites, we feel, would add a level of confusion (i.e. we're not actually assigning inspections to these "sites" as one building could have anywhere from .5 to 2 CSs within). 

If I want to visualize CS structures on the map for inspectors for instance, I can just select distinct System from our new CS_Rooms table and do an in query on the structures layer with those values. So long answer short, no need for a separate ETL. I think we could probably get away with having the Prop ID values for the Structures in the PIP categories table we’re joining to as the guide for what to pull in from the structures layer if that makes sense. If it’s on the PIP categories table grab it from structures kind of thing, if that’s not too circular. If they ever build new rec centers we’ll have to manually add the Prop ID value to the PIP categories value to pull it in via OMPPROPID—but I’m sure those instances will be few and very far between.

**Comment by GeoDan87** [comment]
Only structures with a function of rec center or nature center should be brought in.
