### ISSUE TITLE
OMP should decide if they want tables for referencing category and sub-category

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#16]
We don't want to break anything that exists, but using foreign keys may be safer than using free text.

Note the foreign key added to [tbl_pip_allsites](https://github.com/NYCParks-data/PIP_Sync/blob/master/tbl_pip_allsites.sql) that has a foreign key constraint referencing [tbl_ref_category](https://github.com/NYCParks-data/PIP_Sync/blob/master/tbl_ref_category.sql) and [tbl_ref_subcategory](https://github.com/NYCParks-data/PIP_Sync/blob/master/tbl_ref_subcategory.sql)

**Comment by MEFParks** [comment]
It's probably safer, but we change these so infrequently that it's probably not necessary. Would this just be constraining things to values that already exist?

There's a lot of junk, especially in sub-category (which we don't use for much, but has some limited utility in separating sitting areas out in the small park category) that could probably be cleaned up. Also we may change our categories in the near future. I'm fine with free-text here.

**Comment by GeoDan87** [comment]
Well, we could constrain this columns to values that already exist or add new values. Thanks for the answer here, it sounds like it's worth putting aside for now and keeping as free text.
