### ISSUE TITLE
Is there a need to create any instead of delete triggers

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#20]
An instead of delete trigger could be useful to prevent the deletion of data. It works like this. 

User 1 accidentally deletes records from Table A, but that table has a instead of delete trigger. This trigger is fired and makes the database do something else which could include doing nothing (thus preventing a delete).

**Comment by MEFParks** [comment]
I would have to understand the mechanics a little bit better-- but if this stops records from disappearing from Allsites it's definitely worth exploring as it could serve as a check when things go missing in GIS (as has happened in the past)

**Comment by GeoDan87** [comment]
Closed with #24
