### ISSUE TITLE
Should a merge be added to always ensure that records deleted from tbl_pip_allsites would be added back in

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#26]
This would basically be a stored procedure called as part of the job that inserts records that exist in tbl_ref_allsites, but not in tbl_pip_allsites, signifying that they were deleted (accidentally?) from tbl_pip_allsites.

**Comment by MEFParks** [comment]
I think this might be a bit overkill. We'd see if they didn't have comments or null in the rated field and we could always look back at the audit log to see if something was deleted.

**Comment by GeoDan87** [comment]
We can add a merge for this step.
