### ISSUE TITLE
What do we want to rename vw_pip_compatible_inspected_sites to?

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#28]
Something with an additional 400-500 characters seems to make the most sense. Just tell me what you want and I'll update it as well as all of the references to it.

**Comment by MEFParks** [comment]
Haha, how about Len_the_real__allsites_view?

Open to any suggestions, having a hard time naming it without using Allsites or GIS...

**Comment by GeoDan87** [comment]
vw_pip_sync
