### ISSUE TITLE
Is it okay to default rated = 0 for records that are inserted into tbl_pip_allsites via the trigger trg_fi_tbl_ref_allsites?

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#35]
I made the rated column constrained so that it cannot contain a null value.

However, if we are inserting new records automatically into this table I had to set a default constraint (with a value of 0) on the rated column in the tbl_pip_allsites table. This means that when new records are added to GIS and subsequently your database, they will be added with a [prop id], a 0 value for rated and null values for all other records. 

Does that work for you? Also since I don't make sense 3/4 of the time, I'm happy to clarify.

**Comment by MEFParks** [comment]
Makes sense. 0 as a default is preferred.
