### ISSUE TITLE
Could changing data type of this column to accommodate featurestatus have down stream effects?

### ISSUE THREAD

**Issue by MEFParks** [NYCParks-data/PIP_Sync#39]
https://github.com/NYCParks-data/PIP_Sync/blob/32b77c6927a53a9852d6b34857814549d64fa541/vw_pip_compatible_inspected_sites.sql#L24

currently nvarchar 5

**Comment by GeoDan87** [comment]
@MEFParks, I would say that likely it would not with the following caveats. If this table or value is copied into any other table with the nvarchar(5) data type, if this column is a foreign key for other columns/tables or if it impacts something in the user interface. Luckily I think that I can check the dependencies for this column.

**Comment by GeoDan87** [comment]
For the hell of it, I'll just throw out there, that we could consider using AMPS statuses to dictate workflow. They tend to sometimes lag changes in GIS, but there is an actual workflow and it actually means something in terms of how that record can be interacted with in the system. FeatureStatus might as well have random values you can type in.

**Comment by GeoDan87** [comment]
Featurestatus is now included in vw_pip_compatible_inspected_sites, but currently is not used by any other tables.
