### ISSUE TITLE
ETL for getting parent prop information

### ISSUE THREAD

**Issue by MEFParks** [NYCParks-data/PIP_Sync#46]
https://github.com/NYCParks-data/PIP_Sync/blob/04406dbfb637bb19d8b2236ddd4ac20a8f5345e8/vw_pip_compatible_inspected_sites.sql#L196-L199

It just occurred to me that we might need to rework the prop name and prop location ETLs a bit. Let me know if I'm off base here, but I think the logic should be look to the property layer in cases where OMPPROPID<> GISPROPNUM (i.e. the parent is different from the child), but use OMPROPID to populate the Parent values if OMPPROPID=GISPROPNUM. This would be the case for the prop name and prop location ETLS

This is really clear with the unmapped table because none of the matching parent/children would be found in the Property layer (as they aren't mapped, so there would be null values for Prop name and Prop location. Maybe I'm misreading the query though, and I haven't looked at the new allsites output yet, just something that came up when putting this document together for Peter

**Comment by GeoDan87** [comment]
You're interpretation is correct. I likely translated the document too simplistically and/or missed some things, so apologies. I have no issue at all modifying it, it's your database after all. To make sure I'm correct, this logic would be used just for unmapped or would it be used more broadly? This is exactly what we need the business owner to do, we have to make sure everything is up to spec, so we appreciate it.

**Comment by MEFParks** [comment]
Yeah, I wasn't clear in the Allsites map at all, so your interpretation was correct. I just didn't think through it correctly and that didn't occur to me until I was putting that document together for Peter

So for the property layer we're using GISPROPNUM for everything so the logic doesn't need to apply to that layer. However, for all the other layers the logic should be

If GISPROPNUM= OMPPROPID then use the fields for site name and site location (children) for prop name and prop location (parents). This is a little different across the layers because the fields are named a little differently, but the Allsites map has the correct columns for the children's values by layer.

If GISPROPNUM<> OMPPROPID  (i.e. parent and child not the same/is a subproperty) then use Signname/location for prop name and location where GISPROPNUM in subproperty layer = GISPROPNUM in Property layer

**Comment by GeoDan87** [comment]
select [prop id],
          [site location],
          [site name],
          isnull(r.signname, l.signname) as [prop name]
from openquery([gisdata], 'select * from parksgis.dpr.unmapped_gisallsites_evw') as l 
left join 
         openquery([gisdata], 'select * from parksgis.dpr.property_evw') as r 
 on l.gispropnum = r.gispropnum
 where l.omppropid != l.gispropnum) as t

**Comment by GeoDan87** [comment]
Use this logic for: playground, golf course, greenstreet, unmapped, zone
Do not use this logic for: playground, property, restrictive declaration, school yard to playground (no join to property)

**Comment by GeoDan87** [comment]
Hey @MEFParks, I updated the logic. Perhaps you can check it out when you have a chance to ensure that I didn't miss anything.
