### ISSUE TITLE
Alter logic for syncing structures

### ISSUE THREAD

**Issue by MEFParks** [NYCParks-data/PIP_Sync#56]
the following essential system IDs (have OMPPROPID with Inspection in inspectionmain) are not in the structure function table and therefore not being pulled into the new sync/Allsites. Not sure if that table is still being compiled, but this is what I was able to find

'B406-BLG1208',
'Q401-BLG0533',
'Q470-BLG0554',
'Q468-BLG0553',
'X250-BLG0867',
'R129-BLG1333',
'B088-BLG1036',
'X045-ZN02-BLG0748',
'M037-BLG1546',
'X261-BLG0821',
'X016-BLG0910',
'Q446-BLG0532',
'M010-ZN36-BLG0730',
'X260-BLG0775',
'B210W-02-BLG1106',
'X034-BLG0818',
'R149-BLG0001',

**Comment by GeoDan87** [comment]
@MEFParks I think we need to come up with a near term and longer term solution to this.

**Comment by GeoDan87** [comment]
trg_fi_tbl_ref_allsites should exclude structures. Allsites needs to be adjusted to only do an inner join with structures. All structures should be included in tbl_ref_allsites.

**Comment by GeoDan87** [comment]
Also update this sp_m_tbl_pip_allsites
