### ISSUE TITLE
Create table or view of structures that should have existing values moved into tbl_pip_allsites

### ISSUE THREAD

**Issue by GeoDan87** [NYCParks-data/PIP_Sync#57]
Since structures will not be automatically inserted into tbl_pip_allsites, we need to move any records with existing inspections into this table. The number of records here should be less than the number of structures that existed in the current production version of vw_pip_compatible_inspected_sites.

**Comment by MEFParks** [comment]
Just found some annoying differences between prod and dev that make doing the view the way I want it to on 003. If you look at inspection id =52584 for instance between prod (copy of accessnewpip on data.parks, I think you have access)  and dev (003).

The 'Prop ID' for that record in InspectionMain for dev is BS14 and in Prod it's BS014 (in accordance with the switch made in the SYTPLDG layer). Not sure why it wasn't updated on the copy of dev, Can I just paste the list of sites here and write the query (knowing it will produce the wrong results, but that it will be correct in prod with the correct values in InspectionMain?

**Comment by MEFParks** [comment]
List of Prop IDs from structures to manually add:

QR-05
M010_temp3
QR-01
X034_temp
MR-01
Q468_temp
XR-03
MR-07
X261_temp
BR-03
QR-03
MR-08
MR-10
MR-03
XR-02
QR-04
BR-06
BR-02
XR-05
X250_temp
MR-12
XR-04
MR-02
BR-05
R149-BLG0001
RR-02_temp1
QR-02
MR-06
BR-04
BR-08
MR-11
MR-04
XR-01
BR-07
MR-05
MR-13
BR-01
B406_temp
MR-09

Query used to derive list (it's a bit circular, so you'd have to run it on the old allsites in prod):

SELECT Distinct im.[Prop ID], alls.sourcefc
  FROM [accessNewPIP].[dbo].[InspectionMain] as im
  left join ALLSITES as alls on alls.[prop id]=im.[Prop ID]
  where sourcefc='Structure'
order by sourcefc
