### ISSUE TITLE
Adding two new columns to PIP_Ref and pushing into Allsites with view

### ISSUE THREAD

**Issue by MEFParks** [NYCParks-data/PIP_Sync#66]
https://github.com/NYCParks-data/PIP_Sync/blob/f2e95376191cb56372c29f7fbbffae3ea628bd69/tbl_pip_allsites.sql#L23

Dan can we add two columns to this table:

Rating Category
Site Category

When pushing into the Allsites view would it be possible to do a join of Site Category in the PIP ref table and TYPECATEGORY in the GIS ref where source FC=Property? (i.e. if value in Property layer than take Typecategory, if not use site category)

Ratings category will just pull directly. This is in response to consuming the new categories from Planning. We will continue to use category and subcategory in the background for ratings (we report out small, large, and greenstreet ratings to the Mayor's Office), but these two new (one kinda hybrid) categories will become more visibile to the agency-- category and subcategory would not even push to the DWH copy of Allsites.

Let me know if this doesn't make sense and we can discuss

**Comment by GeoDan87** [comment]
@MEFParks that makes sense to me, I like that your already thinking about the future. Do you know what the data type should be for those fields? 

I also think that we can swing the join in allsites.

**Comment by MEFParks** [comment]
Yeah I was thinking the join would happen in the allsites view for site category (take values from Typecategory in PROP, if none there then add values from the pip table). We'd probably just have blank values in the PIP table for the property layer sites... that way they won't get out of date/there won't be confusion about the authoritative value. Also it makes things easier as it's best for the related table and gis data to live in separate worlds. The allsites view can just have the ETL putting the values together from GIS (typecategory for prop) and our PIP table (Site category for non prop layer) to create the full "Site category" field that can be in the allsites view and whatever we end up putting on DWH.

I think the data types can be whatever they are now for category and sub category, which is nvarchar

Let me know if you think there is a better solution here, too. This is just what I came up with in talking to Alex and trying to figure out how we are going to make use of the new typecategory without disrupting our process too much and having the flexibility to add our own values for the non-property layer sites ( (because this is the only place they are instituting the recategorization
