### ISSUE TITLE
Changing source of Greenstreet prop name and propnum

### ISSUE THREAD

**Issue by MEFParks** [NYCParks-data/PIP_Sync#67]
https://github.com/NYCParks-data/PIP_Sync/blob/f74b0d4a10e064001f9976408ea9fc53a9648cd7/vw_pip_compatible_inspected_sites.sql#L67-L78

Thinking about taking the connection of Greenstreets to the property layer out here. There is too much bad data in the propnum field that it gives weird results. Instead I think signname in greenstreet should be the prop and site name and OMPPROPID in greenstreets should be the prop id and prop num.

This makes sense because greenstreets really shouldn't have parents (they are not really sub properties). If formalized greenstreet groups ever make a reappearance in GIS, then we can pull that number into our propnum field then.

**Comment by GeoDan87** [comment]
Just clarifying that you mean sitename (not signname) in greenstreet should be used for both the prop name and site name? Are we going to keep using the location from property? @MEFParks

**Comment by MEFParks** [comment]
Sorry, Dan. Don't know how I made that mistake. You're right, sitename (all one word, no underscore), not signname. For Prop location and Site location we'd just want "Location" from the GS layer. For Prop num and Prop ID, we'd want OMPPROPID from the GS layer. 

No connection to Property is necessary. We're going to treat Greenstreets like stand alone properties not tied to parents (i.e. not sub-properties). If GS groups ever get formalized in the layer, we can bring that into the workflow as the parent property.
